# Generated by Django 5.2.6 on 2025-09-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='The Orehbeinp dot com', max_length=255),
        ),
    ]
