# Generated by Django 5.2.6 on 2025-09-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperBlog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test_tag',
            field=models.CharField(default='Test complete, without default, it fails', max_length=30),
        ),
    ]
